# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for DanTang(Swift4)
target 'DanTang(Swift4)' do

pod “SwiftyJSON”
pod “MBProgressHUD”
pod “SVProgressHUD”
pod “Alamofire”
pod “SDWebImage”
pod “Kingfisher”
pod “AFNetworking”

end
